name: User Stories Submission
description: User stories are a plain English description of a software feature or function from the end-user perspective.
title: "User story: "
labels: ["user story"]
body:
  - type: input
    id: User_story
    attributes:
      label: User story name
      description: Give your user story a descriptive name.
    validations:
      required: true

  - type: input
    id: Contact_information
    attributes:
      label: Email address
      description: Please share your email.
    validations:
      required: true

  - type: input
    id: first_name
    attributes:
      label: First name
      description: First name
    validations:
      required: true

  - type: input
    id: last_name
    attributes:
      label: Last name
      description: Last name
    validations:
      required: true

  - type: checkboxes
    id: story_type
    attributes:
      label: Type of User Story
      description: Select the type of user story.
      options:
        - label: New feature/tool
        - label: Update to existing feature/tool
        - label: Other
    validations:
      required: true

  - type: input
    id: story_type_other
    attributes: 
      label: Other
      description: If you selected "Other", please briefly describe your story type.
    validations:
      required: true

  - type: checkboxes
    id: story_topic
    attributes:
      label: User Story topic
      description: From the [Mukurtu User Manual](https://mukurtu-user-manual.readthedocs.io/). Can select multiple topics. Specify other if existing topics do not apply.
      options:
        - label: Hosting, site setup, and administration
        - label: Getting started
        - label: Enriching digital heritage
        - label: Managing media
        - label: Managing site users
        - label: Mukurtu dictionary
        - label: Site look and feel
        - label: Roundtrip (import/export)
        - label: Other topics
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Support Tools: 
        - [Microsoft Designer](https://designer.microsoft.com/image-creator)
